#ifndef VERSION_HPP
#define VERSION_HPP

#define OPENMW_VERSION_MAJOR @OPENMW_VERSION_MAJOR@
#define OPENMW_VERSION_MINOR @OPENMW_VERSION_MINOR@
#define OPENMW_VERSION_RELEASE @OPENMW_VERSION_RELEASE@
#define OPENMW_VERSION "@OPENMW_VERSION@"

#define OPENMW_VERSION_COMMIT "@OPENMW_VERSION_COMMIT@"

#endif // VERSION_HPP

