#ifndef ESM4_RECORDS_H
#define ESM4_RECORDS_H

#include <extern/esm4/hair.hpp>
#include <extern/esm4/eyes.hpp>
#include <extern/esm4/race.hpp>
#include <extern/esm4/achr.hpp>
#include <extern/esm4/acre.hpp>
#include <extern/esm4/soun.hpp>
#include <extern/esm4/ltex.hpp>
#include <extern/esm4/acti.hpp>
#include <extern/esm4/appa.hpp>
#include <extern/esm4/armo.hpp>
#include <extern/esm4/book.hpp>
#include <extern/esm4/clot.hpp>
#include <extern/esm4/cont.hpp>
#include <extern/esm4/door.hpp>
#include <extern/esm4/ingr.hpp>
#include <extern/esm4/ligh.hpp>
#include <extern/esm4/misc.hpp>
#include <extern/esm4/stat.hpp>
#include <extern/esm4/gras.hpp>
#include <extern/esm4/tree.hpp>
#include <extern/esm4/flor.hpp>
#include <extern/esm4/furn.hpp>
#include <extern/esm4/weap.hpp>
#include <extern/esm4/ammo.hpp>
#include <extern/esm4/npc_.hpp>
#include <extern/esm4/crea.hpp>
#include <extern/esm4/lvlc.hpp>
#include <extern/esm4/slgm.hpp>
#include <extern/esm4/keym.hpp>
#include <extern/esm4/alch.hpp>
#include <extern/esm4/sbsp.hpp>
#include <extern/esm4/sgst.hpp>
#include <extern/esm4/lvli.hpp>
#include <extern/esm4/lvln.hpp>
#include <extern/esm4/idlm.hpp>
#include <extern/esm4/mstt.hpp>
#include <extern/esm4/txst.hpp>
#include <extern/esm4/scrl.hpp>
#include <extern/esm4/arma.hpp>
#include <extern/esm4/hdpt.hpp>
#include <extern/esm4/term.hpp>
#include <extern/esm4/tact.hpp>
#include <extern/esm4/note.hpp>
#include <extern/esm4/bptd.hpp>
#include <extern/esm4/scpt.hpp>
#include <extern/esm4/regn.hpp>
#include <extern/esm4/land.hpp>
#include <extern/esm4/anio.hpp>
#include <extern/esm4/dial.hpp>
#include <extern/esm4/info.hpp>
#include <extern/esm4/pgrd.hpp>
#include <extern/esm4/road.hpp>
#include <extern/esm4/qust.hpp>
#include <extern/esm4/pack.hpp>
#include <extern/esm4/lgtm.hpp>
#include <extern/esm4/pgre.hpp>
#include <extern/esm4/aspc.hpp>
#include <extern/esm4/imod.hpp>
#include <extern/esm4/pwat.hpp>
#include <extern/esm4/scol.hpp>
#include <extern/esm4/musc.hpp>
#include <extern/esm4/aloc.hpp>
#include <extern/esm4/mset.hpp>
#include <extern/esm4/dobj.hpp>
#include <extern/esm4/clfm.hpp>
#include <extern/esm4/otft.hpp>
#include <extern/esm4/flst.hpp>
#include <extern/esm4/sndr.hpp>
#include <extern/esm4/glob.hpp>

#endif // ESM4_RECORDS_H
