/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Java_com_libopenmw_openmw_GameActivity_getPathToJni
#define _Java_com_libopenmw_openmw_GameActivity_getPathToJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Java_com_libopenmw_openmw_GameActivity_getPathToJni
 * Method:    getPathToJni
 * Signature: (I)I
 */
JNIEXPORT void JNICALL Java_com_libopenmw_openmw_GameActivity_getPathToJni(JNIEnv *env, jobject obj, jstring prompt);

#ifdef __cplusplus
}
#endif
#endif
