#ifndef COMPONENTS_ANDROID_ANDROIDDEPTHBUFFERHELPER_HPP_
#define COMPONENTS_ANDROID_ANDROIDDEPTHBUFFERHELPER_HPP_

class AndroidDepthBufferHelper {
public:
	static int getGlDepthBufferSize();
};

#endif /* COMPONENTS_ANDROID_ANDROIDDEPTHBUFFERHELPER_HPP_ */
