#ifndef OPENMW_COMPONENTS_MYGUIPLATFORM_MYGUICOMPAT_H
#define OPENMW_COMPONENTS_MYGUIPLATFORM_MYGUICOMPAT_H

#include <MyGUI_Prerequest.h>

#if MYGUI_VERSION > MYGUI_DEFINE_VERSION(3, 4, 0)
    #define OPENMW_MYGUI_CONST_GETTER_3_4_1 const
#else
    #define OPENMW_MYGUI_CONST_GETTER_3_4_1
#endif

#endif  // OPENMW_COMPONENTS_MYGUIPLATFORM_MYGUICOMPAT_H
