sampler RT : register(s0);
sampler NormalMap : register(s1);
sampler CausticMap : register(s2);

float4 main_ps(float2 iTexCoord : TEXCOORD0,
       	       float3 noiseCoord : TEXCOORD1,
       	       uniform float4 tintColour) : COLOR
{
	float4 normal = tex2D(NormalMap, noiseCoord) * 2 - 1;
	

	return tex2D(RT, iTexCoord + normal.xy * 0.05) +
	       (tex2D(CausticMap, noiseCoord) / 5) +
	       tintColour ;
}
