/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <osg/Texture2D>



#ifndef _Included_ui_activity_saveCurrentTextureCompressionMode
#define _Included_ui_activity_saveCurrentTextureCompressionMode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Java_ui_activity_GameActivity_saveCurrentTextureCompressionMode
 * Method:    saveCurrentTextureCompressionMode
 * Signature: (I)I
 */
JNIEXPORT void JNICALL Java_ui_activity_GameActivity_saveCurrentTextureCompressionMode(JNIEnv *env, jobject obj, jstring prompt);

#ifdef __cplusplus
}
#endif
#endif
class GlesTextureCompression {
    public:
      static osg::Texture::InternalFormatMode getGLesOsgTextureCompression();
      static void computeCurrentTextureCompression();
    private:
};
