.TH OPENMW "6" "OCTOBER 2013" "Debian" "User Commands"
.SH NAME
openmw-manual - Generate HTML manual for 
.IR openmw(6)
.SH SYNOPSIS
.B openmw-manual
[\fIoption \fR...]
.TP
\fB\-d\fR, \fB\-\-debug\fR NUM
Set debug log level (0 to 3)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print a summary of the options
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information
.SH DESCRIPTION
This tool can be used to generate 5 HTML pages with the documentation
for openmw. The pages cover several topics in detail, including:

\fB*\fP Launcher

.SH "REPORTING BUGS"
Report bugs at http://bugs.openmw.org/
