.TH OPENMW "6" "OCTOBER 2013" "OpenMW" "OpenMW Commands"
.SH NAME
openmw - Reimplementation of the Morrowind Engine 
.SH OPTIONS
.TP
\fB\-\-help\fR
print help message
.TP
\fB\-\-version\fR
print version information and quit
.TP
\fB\-\-data\fR arg (=data)
set data directories (later directories
have higher priority)
.TP
\fB\-\-data\-local\fR arg
set local data directory (highest
priority)
.TP
\fB\-\-fallback\-archive\fR arg (=fallback\-archive)
set fallback BSA archives (later
archives have higher priority)
.TP
\fB\-\-resources\fR arg (=resources)
set resources directory
.TP
\fB\-\-start\fR arg (=Beshara)
set initial cell
.TP
\fB\-\-content\fR arg
content file(s): esm/esp, or
omwgame/omwaddon
.TP
\fB\-\-anim\-verbose\fR [=arg(=1)] (=0)
output animation indices files
.TP
\fB\-\-nosound\fR [=arg(=1)] (=0)
disable all sounds
.TP
\fB\-\-script\-verbose\fR [=arg(=1)] (=0)
verbose script output
.TP
\fB\-\-script\-all\fR [=arg(=1)] (=0)
compile all scripts (excluding dialogue
scripts) at startup
.TP
\fB\-\-script\-console\fR [=arg(=1)] (=0)
enable console\-only script
functionality
.TP
\fB\-\-script\-run\fR arg
select a file containing a list of
console commands that is executed on
startup
.TP
\fB\-\-new\-game\fR [=arg(=1)] (=0)
activate char gen/new game mechanics
.TP
\fB\-\-fs\-strict\fR [=arg(=1)] (=0)
strict file system handling (no case
folding)
.TP
\fB\-\-encoding\fR arg (=win1252)
Character encoding used in OpenMW game
messages:
.IP
win1250 \- Central and Eastern European
such as Polish, Czech, Slovak,
Hungarian, Slovene, Bosnian, Croatian,
Serbian (Latin script), Romanian and
Albanian languages
.IP
win1251 \- Cyrillic alphabet such as
Russian, Bulgarian, Serbian Cyrillic
and other languages
.IP
win1252 \- Western European (Latin)
alphabet, used by default
.TP
\fB\-\-fallback\fR arg
fallback values
.TP
\fB\-\-activate\-dist\fR arg (=\-1)
activation distance override
.PP
.SH "REPORTING BUGS"
Report bugs at http://bugs.openmw.org/
