name: Release

on:
  push:
      tags:
        - openmw-**

jobs:
  Windows:
    uses: ./.github/workflows/windows.yml
    with:
      image: "2022"
      build-type: Release
      package: true
      release: true
    secrets: inherit
  MacOS:
    strategy:
      fail-fast: true
      matrix:
        args:
          - image: macos-26
          - image: macos-26-intel
    uses: ./.github/workflows/macos.yml
    with:
      image: ${{ matrix.args.image }}
      build-type: Release
